[phases.setup]
nixPkgs = ["ruby_3_3", "nodejs_20", "bun"]

[phases.install]
cmds = ["bundle install", "bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
