[build]
builder = "nixpacks"
buildCommand = "bundle install && bun install && bun run build"

[deploy]
startCommand        = "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
healthcheckPath     = "/up"
healthcheckTimeout  = 60
restartPolicyType   = "on_failure"
restartPolicyMaxRetries = 3
